# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'index.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QMainWindow
from ..MainGame.MainGame import Ui_MainGame


class Ui_Setting(QMainWindow):
    def __init__(self, parent=None):
        super(Ui_Setting, self).__init__(parent)

        self.mainGame = object()

        self.Saolei_w = 9
        self.Saolei_h = 9
        self.Saolei_boom_num = 10

        self.setObjectName("Setting")
        self.resize(384, 351)
        self.setMinimumSize(QtCore.QSize(384, 351))
        self.setMaximumSize(QtCore.QSize(384, 351))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.setFont(font)
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(139, 30, 121, 51))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(49, 90, 111, 21))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self)
        self.label_3.setGeometry(QtCore.QRect(49, 160, 111, 21))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.SaoLei_Width = QtWidgets.QLineEdit(self)
        self.SaoLei_Width.setPlaceholderText("9")
        self.SaoLei_Width.setGeometry(QtCore.QRect(209, 90, 113, 20))
        self.SaoLei_Width.setObjectName("SaoLei_Width")
        self.SaoLei_Height = QtWidgets.QLineEdit(self)
        self.SaoLei_Height.setPlaceholderText("9")
        self.SaoLei_Height.setGeometry(QtCore.QRect(209, 160, 113, 20))
        self.SaoLei_Height.setObjectName("SaoLei_Height")
        self.SaoLei_count_num = QtWidgets.QLineEdit(self)
        self.SaoLei_count_num.setPlaceholderText("10")
        self.SaoLei_count_num.setGeometry(QtCore.QRect(209, 230, 113, 20))
        self.SaoLei_count_num.setObjectName("SaoLei_count_num")
        self.label_4 = QtWidgets.QLabel(self)
        self.label_4.setGeometry(QtCore.QRect(49, 230, 131, 21))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.newGame_btn = QtWidgets.QPushButton(self)
        self.newGame_btn.setGeometry(QtCore.QRect(130, 290, 101, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.newGame_btn.setFont(font)
        self.newGame_btn.setStyleSheet("QPushButton:hover{\n"
            "    background-color: qlineargradient(\n"
            "    spread:pad,x1:0,x2:0,y1:0,y2:1,\n"
            "    stop: 0 rgba(170, 255, 255,250),\n"
            "    stop: 0.5 rgba(0, 209, 209,255), \n"
            "    stop: 1 rgba(170, 255, 255,250));\n"
            "    color:rgb(0,0,0);\n"
            "    border-radius:4px;\n"
            "    border: 1px solid #333;\n"
            "}")
        self.newGame_btn.setAutoDefault(True)
        self.newGame_btn.setDefault(False)
        self.newGame_btn.setFlat(False)
        self.newGame_btn.setObjectName("newGame_btn")
        self.newGame_btn.clicked.connect(self.newGame_btn_click)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def newGame_btn_click(self):
        if self.SaoLei_Width.text():
            self.Saolei_w = int(self.SaoLei_Width.text())
        if self.SaoLei_Height.text():
            self.Saolei_h = int(self.SaoLei_Height.text())
        if self.SaoLei_count_num.text():
            self.Saolei_boom_num = int(self.SaoLei_count_num.text())
        self.mainGame = object()
        self.mainGame = Ui_MainGame(self.Saolei_w, self.Saolei_h, self.Saolei_boom_num)
        # self.mainGame.setWindowModality(Qt.ApplicationModal)
        self.hide()
        self.mainGame.show()
        self.mainGame._signal.connect(self.get_status)

    def get_status(self, status: int):
        if status == 1:
            self.show()
            self.SaoLei_Width.setText("")
            self.SaoLei_Height.setText("")
            self.SaoLei_count_num.setText("")
        else:
            self.close()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Setting", "设置"))
        self.label.setText(_translate("Setting", "设置"))
        self.label_2.setText(_translate("Setting", "高度(9-24)(H) ："))
        self.label_3.setText(_translate("Setting", "宽度(9-24)(W) ："))
        self.label_4.setText(_translate("Setting", "雷数(10-668)(M) ："))
        self.newGame_btn.setText(_translate("Setting", "新游戏"))
